### ISSUE TITLE
Criar uma lista com 15 nomes de startups para criar os mashups

### ISSUE THREAD

**Issue by teles** [startup-mashup/startup-mashup.github.io#1]

**Comment by teles** [comment]
1. Duolingo
2. Uber
3. Airbnb
4. Linkedin
5. Snapchat
6. Dropbox
7. Spotify
8. Pinterest

**Comment by woliveiras** [comment]
Slack

**Comment by woliveiras** [comment]
GuiaBolso
NuBank

**Comment by woliveiras** [comment]
Eventick

**Comment by teles** [comment]
Disqus
Coursera
Khan Academy

**Comment by teles** [comment]
Hootsuite

**Comment by teles** [comment]
Tinder

**Comment by teles** [comment]
ifood

**Comment by teles** [comment]
1. Duolingo
2. Uber
3. Airbnb
4. Linkedin
5. Snapchat
6. Dropbox
7. Spotify
8. Pinterest
9. Slack
10. GuiaBolso
11. NuBank
12. Eventick
13. Disqus
14. Coursera
15. Khan Academy
16. Hootsuite
17. Tinder
18. iFood
19. Netflix
20. Whatsapp
